# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
   runs-on: ubuntu-latest
     steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
       run: chmod +x gradlew
    - name: Build with Gradle
       run: ./gradlew build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ID}}
        aws-secret-access-key: ${{secrets.AWS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}

    - name: Login to AWS ECR
        id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Push To ECR
       run: ./gradlew jib
